### ISSUE TITLE
strange use of has_role_assignment

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#11]
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/stats.php#L86

Capabilities should be used rather than role assignment checks - you should also not hard-code the roleid as many organisations create their own roles and you cannot rely on the role still existing.

**Comment by danmarsden** [comment]
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/view.php#L151

**Comment by fearcraftor** [comment]
Fixed
https://github.com/Celumproject/moodle-mod_domoscio/commit/f4c32cc520ab61ed0fda2b4d71c99dfe9152ae0c

Florent
Domoscio
