### ISSUE TITLE
anonymous access to auth.php

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#12]
This file appears to allow anonymous access and could expose private information (although I have not tested this) - it should be clear within the comments in the file that anonymous access is intended and there is no risk associated with this.

https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/sdk/auth.php

**Comment by fearcraftor** [comment]
This file is not used anymore. Deleted

https://github.com/Celumproject/moodle-mod_domoscio/commit/dfd6e190effc8f0d489466a093dd8aeeab5d5e40

Florent
Domoscio
