### ISSUE TITLE
invalid file in repo

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#13]
looks like this file was included accidentally: (copy of install.xml)

https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/db/install.xml~

**Comment by fearcraftor** [comment]
File deleted
https://github.com/Celumproject/moodle-mod_domoscio/commit/3a6c8b39cfb95da10ae4830626a10677a9706947

Thank you

Florent
Domoscio
