### ISSUE TITLE
class and function names too generic

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#14]
Please follow coding guideline standards for naming of classes and custom fuctions within your plugin.

for example "quiz_form" is too generic and not specific to the domoscio plugin. take a look at the "frankenstyle" prefix naming conventions in the moodledocs for more details.

**Comment by danmarsden** [comment]
also the Class autoloading docs for correct naming of classes within a plugin.

**Comment by fearcraftor** [comment]
Fixed
https://github.com/Celumproject/moodle-mod_domoscio/commit/703636e6cd481e8a753e69fb28125df8fdcd1c26

Florent

Domoscio
