### ISSUE TITLE
parameters used directly inside in-line sql

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#15]
Please modify the direct SQL queries you have written to use correct DML syntax in Moodle with parameterisation rather than including php vars directly into in-line sql.

more information on using parameters is here:
https://docs.moodle.org/dev/Data_manipulation_API#Main_info

**Comment by fearcraftor** [comment]
Inline vars in SQL queries fixed, see commit https://github.com/Celumproject/moodle-mod_domoscio/commit/8cf50e28b4aee90a287acf2ed6ea3e5d4cfc9229
Thank you for your review
