### ISSUE TITLE
celltest.php vulnerable to CSRF

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#21]
celltest defines it's own form without using standard moodle forms and does not implement sesskey checking.
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/celltest.php#L84

more info here:
https://docs.moodle.org/dev/Security:Cross-site_request_forgery

**Comment by fearcraftor** [comment]
At first, celltest.php was intented to allow course creators to create their own tests apart from Moodle question engine and we began to wrote something. But as the plugin moved to use the most from course content, the celltest form wasn't a priority for us anymore and these functionalities planned to be implemented in a next plugin version.

As for now, our plugin didn't need celltest.php at all to work, we decided to remove these files for now and we'll work in a further version of the plugin for better implementation of that functionality.

https://github.com/Celumproject/moodle-mod_domoscio/commit/7bb6cc07f3c7a32c9eb50f9e5218cd2897a5b0c1

**Comment by danmarsden** [comment]
great! :-)

**Comment by mudrd8mz** [comment]
I am confused now. The latest version of the plugin published at https://moodle.org/plugins/pluginversion.php?id=9955 has the file celltest.php included

**Comment by fearcraftor** [comment]
Sorry for that, I'll re-push plugin without that file
