### ISSUE TITLE
hard-coded strings

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#22]
There still seems to be some hard-coded strings - example:

https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/create_notion.php#L59

please review other parts of your code to find other similar issues.

**Comment by danmarsden** [comment]
here's another example:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/stats_adv.php#L139

I spotted a few others in your code.

**Comment by fearcraftor** [comment]
These are fixed with latest commit https://github.com/Celumproject/moodle-mod_domoscio/commit/6ee8bb4c35aa776b3ebd6d6edb9d163ff6214b2b

**Comment by danmarsden** [comment]
just took a look at one of your files and spotted:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/celltest.php#L131
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/celltest.php#L133

the form values X and Update are hardcoded strings - you might consider using the delete/update icons instead too? eg  $OUTPUT->pix_icon('t/delete'

**Comment by danmarsden** [comment]
another one that's been missed:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/lib.php#L1438

**Comment by mudrd8mz** [comment]
Should this be closed now? Or are you waiting for us to review all the lines to see if there is no other hard-coded string? ;-)
