### ISSUE TITLE
data_submitted used but not validated cleaned, possible XSS vulnerabilities

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#23]
data_submitted() is raw $_POST - your code uses data from this function without cleaning or validating.

in some cases this stores raw $_POST in the $session like here:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/results.php#L146

please review all uses of data_submitted and replace with either optional/require_param where possible or make sure it is very clear that the data is being validated and cleaned to prevent security issues.

**Comment by fearcraftor** [comment]
Raw data_submitted isn't used anymore and are repalced by optional params, see latest commit https://github.com/Celumproject/moodle-mod_domoscio/commit/6ee8bb4c35aa776b3ebd6d6edb9d163ff6214b2b
