### ISSUE TITLE
backticks inside in-line sql

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#24]
this doesn't look right to me:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/lib.php#L614

it might work in MySql but will fail in everything else. Can you please use PostGres for your own internal testing? if it works in PostGres it is more likely to work in all other supported dbs like MS Sql etc.

**Comment by fearcraftor** [comment]
Fixed, see commit https://github.com/Celumproject/moodle-mod_domoscio/commit/d3ddb1b7269b570ebdf61cd3917f383de10d0ee0

The plugin was tested with Postgres and works fine, one bug detected and fixed ("user" column in domoscio_knode_students changed into "userid" as "user" is postgres reserved keyword)

**Comment by danmarsden** [comment]
great! - nice to see all those backticks get removed..a long time ago (maybe Moodle 1.4) I remember removing a lot of backticks from the Moodle core code to improve postgres support
