### ISSUE TITLE
consider using recordsets

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#25]
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/linkto.php#L78

you should consider using recordsets when dealing with large numbers of records from a table like this - take a look at the documentation around the get_recordset() functions for more info.

**Comment by fearcraftor** [comment]
These queries now use recordset since last commit https://github.com/Celumproject/moodle-mod_domoscio/commit/6ee8bb4c35aa776b3ebd6d6edb9d163ff6214b2b
