### ISSUE TITLE
all scorm objects in site exposed

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#6]
This line appears to show all scorm packages on the site to all users that can view this page:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/linkto.php#L81

it should be filtered by the current course right? - students shouldn't be able to see scorm packages from other courses.

**Comment by fearcraftor** [comment]
At the begining we wanted to allow course creator to pickup SCORMs from each courses but we see know the problem in terms of security. We need to know which solution is approved by Moodle before : 

1/ Grant access for course creator to all SCORMs from the current course and others which he has access ?
2/ Only allow course creator to select SCORM's from the current course ?

**Comment by danmarsden** [comment]
Only SCORM packages/courses that are visible to the current user should be
shown. You should be checking a specific capability within the course using
something like the function get_user_capability_course() using something
like the capability "'mod/scorm:viewreport" - you should also then use the
standard SCORM player.php instead of writing your own.

Dan

**Comment by fearcraftor** [comment]
Fixed https://github.com/Celumproject/moodle-mod_domoscio/commit/3644e6c9211c95044db5dcc831455a032a82691c

Now, plugin check : 
- in Linkto view and display all SCORM packages and Quiz modules the course creator is able to view.
- in doQuiz.php view if student has capability to see SCORM package or Quiz module selected by the course creator

Florent
Domoscio
