### ISSUE TITLE
$CFG->prefix is deprecated

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#7]
it looks like you have used direct calls to $CFG->prefix in SQL like here:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/linkto.php#L121

You should wrap the table names in curly braces like this:
SELECT * FROM {knowledge_node_questions}

Instead of using direct calls to $CFG

**Comment by fearcraftor** [comment]
Fixed, see commit for details
https://github.com/Celumproject/moodle-mod_domoscio/commit/3a6c8b39cfb95da10ae4830626a10677a9706947

Thank you for your fast and efficient report

Florent
Domoscio
