### ISSUE TITLE
strings hardcoded

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#8]
a number of strings within the plugin have been hardcoded:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/linkto.php#L145
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/stats_adv.php#L104

and several others. These should be moved into the plugin language files.

**Comment by danmarsden** [comment]
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/quiz.php#L62
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/quiz.php#L131
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/quiz.php#L146
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/results.php#L61

**Comment by fearcraftor** [comment]
Lasts strings hardcoded have been cleaned and moved into lang files
https://github.com/Celumproject/moodle-mod_domoscio/commit/881184ab8c791ca8d338d217f52af14833f33515
Thanks

Florent
Domoscio
